# Generated by Django 4.1.2 on 2022-11-24 10:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('content', models.CharField(max_length=1024)),
                ('answer', models.CharField(max_length=1024)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=1024)),
                ('phone', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
                ('paper1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='paper1', to='data.paper')),
                ('paper2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='paper2', to='data.paper')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('paper1_answer', models.CharField(max_length=1024)),
                ('paper2_answer', models.CharField(max_length=1024)),
                ('result', models.IntegerField()),
                ('submit_time', models.DateTimeField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.user')),
            ],
        ),
    ]
