# Generated by Django 4.1.2 on 2022-11-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
