# Generated by Django 4.1.2 on 2022-11-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_enrollment_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='submit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
